export const topicConstants = {
    'GET_ALL_TOPICS': 'forumx/GET_ALL_TOPICS',
    'GET_TOPIC': 'forumx/GET_TOPIC',
    'UPDATE_TOPIC': 'forumx/UPDATE_TOPIC',
    'DELETE_TOPIC': 'forumx/DELETE_TOPIC',
    'LOAD_SEARCH_POST': 'forumx/LOAD_SEARCH_POST,'
};

export const postConstants = {
    'GET_POST_SUCCESS': 'forumx/GET_POST_SUCCESS',
    'GET_POST_FAILURE': 'forumx/GET_POST_FAILRE',
    'CREATE_POST_SUCCESS': 'forumx/CREATE_POST/SUCCESS',
    'CREATE_POST_FAILURE': 'forumx/CREATE_POST/FAILURE',
    'UPDATE_POST_SUCCESS': 'forumx/UDPATE_POST_SUCCESS',
    'UPDATE_POST_FAILURE': 'forumx/UDPATE_POST_FAILURE',
    'DELETE_POST_SUCCESS' : 'forumx/DELETE_POST_SUCCESS',
    'DELETE_POST_FAILURE' : 'forumx/DELETE_POST_FAILURE',
    'RESET_POST_STATE': 'forumx/RESET_POST_STATE',
    'CLEAR_POST_ERROR' : 'forumx/CLEAR_POST_ERROR',
    'CLEAR_CURRENT_POST': 'forumx/CLEAR_CURRENT_POST',
};

export const commentConstants = {
    'CREATE_COMMENT_SUCCESS': 'forumx/CREATE_COMMENT_SUCCESS',
    'CREATE_COMMENT_FAILURE': 'forumx/CREATE_COMMENT_FAILURE',
    'UPDATE_COMMENT_SUCCESS': 'forumx/UDPATE_COMMENT_SUCCESS',
    'UPDATE_COMMENT_FAILURE': 'forumx/UDPATE_COMMENT_FAILURE',
    'DELETE_COMMENT_SUCCESS' : 'forumx/DELETE_COMMENT_SUCCESS',
    'DELETE_COMMENT_FAILURE' : 'forumx/DELETE_COMMENT_FAILURE',
    'RESET_COMMENT_STATE': 'forumx/RESET_COMMENT_STATE',
    'CLEAR_COMMENT_ERROR' : 'forumx/CLEAR_COMMENT_ERROR',
};


export const searchConstants = {
    'SEARCH_RENDER_UPDATE': 'forumx/SEARCH_RENDER_UPDATE',
    'SEARCH_POST_SUCCESS': 'forumx/SEARCH_POST_SUCCESS',
    'SEARCH_POST_FAILURE': 'forumx/SEARCH_POST_FAILURE',
    'CLEAR_SEARCH_RESULTS': 'forumx/CLEAR_SEARCH_RESULT',
};


export const logsConstants = {
    'GET_ACTIVITY_LOGS' : 'forumx/GET_ACTIVITY_LOGS',
};

export const successConstants = {
    'SET_SUCCESS_MESSAGE': 'forumx/SET_SUCCESS_MESSAGE',
    'CLEAR_SUCCESS_MESSAGE': 'forumx/CLEAR_SUCCESS_MESSAGE',
};
