export const userConstants = {
    REGISTER_OAUTH_SUCCESS: "USER_REGISTER_OAUTH_SUCCESS",
    REGISTER_OAUTH_FAILURE: "USER_REGISTER_OAUTH_FAILURE",

    REGISTER_OTP_SUCCESS: "USER_REGISTER_OTP_SUCCESS",
    REGISTER_OTP_FAILURE: "USER_REGISTER_OTP_FAILURE",

    REGISTER_USERNAME_REQUEST: 'USER_REGISTER_USERNAME_REQUEST',
    REGISTER_PASSWORD_REQUEST: 'USER_REGISTER_PASSWORD_REQUEST',
    REGISTER_USERNAME_VALID: "USER_REGISTER_USERNAME_VALID",
    REGISTER_PASSWORD_VALID: "USER_REGISTER_PASSWORD_VALID",

    REGISTER_USERNAME_REQUEST_LIMIT: "USER_REGISTER_USERNAME_REQUEST_LIMIT",
    REGISTER_PASSWORD_REQUEST_LIMIT: "USER_REGISTER_PASSWORD_REQUEST_LIMIT",

    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    LOGIN_SUBMITTED_SUCCESS: 'USER_LOGIN_SUBMITTED_SUCCESS',
    LOGIN_SUBMITTED_FAILURE: 'USER_LOGIN_SUBMITTED_FAILURE',

    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

    CLEAR_LOGIN_ERROR: 'CLEAR_LOGIN_ERROR',
    CLEAR_REGISTER_ERROR: 'CLEAR_REGISTER_ERROR',

    RESET_PASSWORD_SUCCESS: 'USER_RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'USER_RESET_PASSWORD_FAILURE',

    EDIT_PASSWORD_SUCCESS: 'USER_EDIT_PASSWORD_SUCCESS',
    EDIT_PASSWORD_FAILURE: 'USER_EDITPASSWORD_FAILURE',

    REFRESH_TOKEN_SUCCESS: 'USER_REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_FAILURE: 'USER_REFRESH_TOKEN_FAILURE',

    'CHANGE_PASSWORD_CHECK_REQUESTING': 'USER_CHANGE_PASSWORD_CHECK_REQUESTING',
    'CHANGE_PASSWORD_CHECK_SUCCESS' : 'USER_CHANGE_PASSWORD_CHECK_SUCCESS',
    'CHANGE_PASSWORD_CHECK_FAILURE' : 'USER_CHANGE_PASSWORD_CHECK_FAILURE',

}